// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2A3lR-FH6toO4S8ueRYcGEfji49oHjAM',
    appId: '1:139610410740:android:a30a4bd7dfd2c26be958a1',
    messagingSenderId: '139610410740',
    projectId: 'ntfy-fcm-2fcf1',
    storageBucket: 'ntfy-fcm-2fcf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwXw8ItSHdeB4g_iXU1rXII4zIPF2vSjg',
    appId: '1:139610410740:ios:e6a328283d42f521e958a1',
    messagingSenderId: '139610410740',
    projectId: 'ntfy-fcm-2fcf1',
    storageBucket: 'ntfy-fcm-2fcf1.firebasestorage.app',
    androidClientId: '139610410740-itrdqcfm2j2omj0afva5nc8h3hosbhpj.apps.googleusercontent.com',
    iosClientId: '139610410740-7d4uhhhdfbil27a5al47mv18hk0gkror.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPlayground',
  );
}
